language: php

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_script:
  - cp .env.travis .env
  - cp phpunit.xml.dist phpunit.xml
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit