language: php

php:
  - 7.1
  - 7.2
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - cp .env.travis .env
  - cp phpunit.xml.dist phpunit.xml
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit